### ISSUE TITLE
Docker image: add few more tags

### ISSUE THREAD

**Issue by icamys** [tarantool/nginx_upstream_module#100]
Please add a few more tags to docker image. At the moment there are only two tags: `v2.3.7` and `latest`. As I mentioned in #99, the `v2.3.7` is still buggy and the only tag that can be used is `latest`.

The problem is that image downloaded today with tag `latest` may be not the same as image tagged as `latest` tomorrow on production server.

It would be nice to have few more digital tags that do not imply any changes in future and can be safely included in our project configs.

**Comment by opomuc** [comment]
Added tags `v2.4.6`, `v2.4.7` (old latest), `v2.5-rc1`, `v2.5-rc2` to Docker. 
For `v2.5-rc1` and `v2.5-rc2` builds are in progress, should finish shortly.
