### ISSUE TITLE
[Docker] Use LuaJIT from Tarantool repository

### ISSUE THREAD

**Issue by AlexMasterov** [tarantool/nginx_upstream_module#101]
The current LuaJIT version: `2.0.5`
Tarantool fork version: `2.1.0-beta3` (+[GC64 mode for x64](https://github.com/tarantool/luajit/blob/614040402b05d37a3b7f2842fdecf7fb901d0651/src/Makefile#L114))

It seems to work, the example: [nginx-tarantool/Dockerfile](https://github.com/AlexMasterov/dockerfiles/blob/d46a6969922dd38267047a62d8a33a069df8cf45/alpine-nginx-tarantool/Dockerfile).

**Comment by racktear** [comment]
Hi,

Is there any particular reason why you need it?

**Comment by dedok** [comment]
Still actual?

**Comment by dedok** [comment]
@AlexMasterov I close this for awhile, if you still have this problem please reopen this issue. Thanks.
