### ISSUE TITLE
version typo

### ISSUE THREAD

**Issue by hellower** [tarantool/nginx_upstream_module#104]
src/ngx_http_tnt_version.h

#define NGX_HTTP_TNT_MODULE_VERSION_STRING "v2.5-rc2"
==>
#define NGX_HTTP_TNT_MODULE_VERSION_STRING "v2.5"

**Comment by dedok** [comment]
Thx! Fixed in 1a3f92cd3e3e9f36ce1d1a2927d9c77fe69ceb51
