### ISSUE TITLE
ngx_http_tnt_module.c:1351:14: error: comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by m3m3m3m3** [tarantool/nginx_upstream_module#109]
error when trying to install nginx upstream module in ubuntu 16.04 (fresh OS install). nginx 1.13.7
make build-all
make __install

        /root/nginx_upstream_module/src/ngx_http_tnt_module.c
/root/nginx_upstream_module/src/ngx_http_tnt_module.c: In function 'ngx_http_tnt_urldecode':
/root/nginx_upstream_module/src/ngx_http_tnt_module.c:1351:14: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     while (s < src->len) {
              ^
/root/nginx_upstream_module/src/ngx_http_tnt_module.c:1355:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         if (c == '%' && s + 2 < src->len) {
                               ^
/root/nginx_upstream_module/src/ngx_http_tnt_module.c: In function 'ngx_http_tnt_format_prepare':
/root/nginx_upstream_module/src/ngx_http_tnt_module.c:1525:29: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                     if (tmp > conf->select_limit_max) {
                             ^
/root/nginx_upstream_module/src/ngx_http_tnt_module.c:1530:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                         (tmp > conf->select_limit_max ?
                              ^
/root/nginx_upstream_module/src/ngx_http_tnt_module.c:1531:52: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
                             conf->select_limit_max : tmp);
                                                    ^
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I/root/nginx_upstream_module/third_party -I/root/nginx_upstream_module/third_party/yajl/build/yajl-2.1.0/include -I/root/nginx_upstream_module/third_party/msgpuck -I/root/nginx_upstream_module/src -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs \
        -o objs/ngx_modules.o \
        objs/ngx_modules.c
sed -e "s|%%PREFIX%%|/usr/local/nginx|" \
        -e "s|%%PID_PATH%%|/usr/local/nginx/logs/nginx.pid|" \
        -e "s|%%CONF_PATH%%|/usr/local/nginx/conf/nginx.conf|" \
        -e "s|%%ERROR_LOG_PATH%%|/usr/local/nginx/logs/error.log|" \
        < docs/man/nginx.8 > objs/nginx.8
cc1: all warnings being treated as errors
objs/Makefile:1211: recipe for target 'objs/addon/src/ngx_http_tnt_module.o' failed
make[3]: *** [objs/addon/src/ngx_http_tnt_module.o] Error 1
make[3]: Leaving directory '/root/nginx_upstream_module/nginx'
Makefile:8: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/root/nginx_upstream_module/nginx'
Makefile:46: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/root/nginx_upstream_module'
Makefile:49: recipe for target '__install' failed
make: *** [__install] Error 2

same error happens when compiling nginx from source:
wget http://nginx.org/download/nginx-1.13.7.tar.gz
tar -xvf nginx-1.13.7.tar.gz
cd nginx-1.13.7
 ./configure --prefix=/usr/local/nginx --add-module=/root/nginx_upstream_module --with-cc-opt='-I /root/nginx_upstream_module/third_party/msgpuck -I /root/nginx_upstream_module/third_party/yajl/build/yajl-2.1.0/include' \
make
make install

which nginx   = no  nginx installed

**Comment by dedok** [comment]
Fixed in 6642f936fa81ac2198b2fd58c755850c4cb0d203

@m3m3m3m3, hi! Thank to you this report. Master is currently under development, it is stable, but it could be broken sometime.

**Comment by dedok** [comment]
I'm closing this issue, if you will have this problem again, please reopen this issue.
