### ISSUE TITLE
Unescape option not working correctly

### ISSUE THREAD

**Issue by dokshina** [tarantool/nginx_upstream_module#120]
Because of incrementing variable `s` in this line

https://github.com/tarantool/nginx_upstream_module/blob/6c5696b9e6ef5f227d3218d7b9ab99f1dddeea3e/src/ngx_http_tnt_module.c#L1617

this check 

https://github.com/tarantool/nginx_upstream_module/blob/6c5696b9e6ef5f227d3218d7b9ab99f1dddeea3e/src/ngx_http_tnt_module.c#L1619

is false if the last string character is urlencoded.

So, the last urlencoded character will be ignored.
For example, for string `%7B%7D` will be returned `{%7D`.

**Comment by dedok** [comment]
Fixed in: 1a6208051f5a219c7783cfa8910496dcff6faec8

**Comment by dedok** [comment]
I closed this. Please feel free to reopen if error still exists.
