### ISSUE TITLE
Module doesn't support tarantool since version 2.1

### ISSUE THREAD

**Issue by Kasen** [tarantool/nginx_upstream_module#132]
Seems like upstream module serializes hashmap to invalid format. So if this construction:
```
{
    params: [],
    meta: {"ttl" = 123 }
}
```
will be passed to upstream module then error occurs:
```
{"id":0,"error":{"message":"Invalid MsgPack - packet body","code":-32788}}
```

This problem reproduces on tarantool since commit https://github.com/tarantool/tarantool/commit/3fb69c15ecfe8c8aa0576a7974e61958f51f7667

**Comment by dedok** [comment]
Will take a look this weekend. Also could please you please add your Nginx.conf and Tarantool stored procedure?

**Comment by hpvd** [comment]
is there any news on this topic yet?
