### ISSUE TITLE
JSON RPC one location issue

### ISSUE THREAD

**Issue by zloidemon** [tarantool/nginx_upstream_module#20]
JSON RPC usually uses with one location where you pass method and that method called.  For that case would be nice fix that:

Call location /api with data:
```
 {"jsonrpc": "2.0", "method": "sum", "params": [1,2,4], "id": "1"}
```

That means module has to call remote tarantool server method *sum* and pass params.

**Comment by dedok** [comment]
@zloidemon this feature is present. Sorry for misunderstood.
