### ISSUE TITLE
export tarantool api for other nginx modules

### ISSUE THREAD

**Issue by 0xBF** [tarantool/nginx_upstream_module#22]
Хочется переиспользовать код взаимодействия с тарантулом в своем nginx-модуле.

По сути, нам для этого требуется из сишного кода
- инициализировать новый upstream со своими параметрами (это, вроде, можно и так делать)
- делать вызовы тарантул-функции с параметрами
- получать статус выполнения функции (что вернул тарантул/ошибку тарантула/ошибку связи)

Что-то в духе

```
void callback(id, result) {
 ...
}

void some_nginx_handler(..) {
  tnt_call(func_name, func_args, id, &callback);
}
```

**Comment by dedok** [comment]
As I know this issue is not actual
