### ISSUE TITLE
Strict REST compatibility

### ISSUE THREAD

**Issue by Sulverus** [tarantool/nginx_upstream_module#24]
Need to allow GET, PUT and DELETE queries

**GET**
for url /nginx_proxy/func_name/
must call stored procedure named `func_name` without arguments

after #25 it must call stored procedure with request object

**PUT**
Tarantool api is equal to POST

**DELETE**
Tarantool api is equal to POST

**Comment by dedok** [comment]
HEAD of v0.2.0-part-1

**Comment by Sulverus** [comment]
Integrated with UCP. Now checking with complete load test(100kk requests)
