### ISSUE TITLE
Fix inverted method selection in http path

### ISSUE THREAD

**Issue by Sulverus** [tarantool/nginx_upstream_module#27]
* In http path method name detection name = **fisrt** path element. For example, query `http://host.com/one/two/three/` method name is equeal `three`, must be `one`
* If there is a body in request(POST, PUT), and body contains `method` field, need to disable http path method name detection
* (optional) need to update `README.md` with upstream configuration options

**Comment by dedok** [comment]
done in head of v0.2.0-part-1
