### ISSUE TITLE
Disable response wrapper

### ISSUE THREAD

**Issue by Sulverus** [tarantool/nginx_upstream_module#30]
Default nginx answer is:
```json
{
  "id": 0,
  "result": [
    [
      {
        "debug": {
          "front": "app-1",
          "auth": false,
          "source": false
        },
        "status": {
          "code": 200,
          "text": "OK"
        }
      }
    ]
  ]
}
```

We need to switch it to raw tarantool response:
```json
      {
        "debug": {
          "front": "app-1",
          "auth": false,
          "source": false
        },
        "status": {
          "code": 200,
          "text": "OK"
        }
      }
```
it can be configurable with `tnt_raw on;` option

**Comment by dedok** [comment]
Branch: v2.0-part2

Now available 2 new options for this feature

Currently protocol are {id: INT, result: [[OBJ]] }, where id/result - add tnt module, [[]] - tarantool multireturn

tnt_pure_result [on/off];
if 'on' - disable "id" and "result"

tnt_multireturn_skip_count [SIZE];
if > 0 then module will skip one or more multireturn parts, for instance

nginx.conf
tnt_pure_result on;


tnt_multireturn_skip_count 0;
call -- {'method': 'echo_2', 'params': [1,2], id: 1}
result -- [[1, 2]]

tnt_multireturn_skip_count 1;
call -- {'method': 'echo_2', 'params': [1,2], id: 1}
result -- [1, 2]

tnt_multireturn_skip_count 2;
call -- {'method': 'echo_2', 'params': [1,2], id: 1}
result -- 1  <<--- this BUG, will fix ASAP

**Comment by dedok** [comment]
PS More examples can be found at test/v20_features.py  and misc/nginx.dev.conf
