### ISSUE TITLE
Transparent proxy to the tarantool procedure via nginx

### ISSUE THREAD

**Issue by zloidemon** [tarantool/nginx_upstream_module#42]
As usual some projects can have any protocols over HTTP or serialization isn't equal JSON like google pb, apache avro and etc. Apache avro has own content-type:

```
Content-Type: "avro/binary"
```

Nginx module should pass all data to lua procedure into tarantool without deserialization data with headers like that:

```
function someaction(client, headers, params, data)
    -- do something here
    return headers, result
end
```
- client should contain ip address and other information
- headers are lua table
- params pased params to http request and also lua table
- data is body of request

Where  someaction() is **nginx** location where will passed data over HTTP.

**Comment by dedok** [comment]
in https://github.com/tarantool/nginx_upstream_module/commit/05c997c41ced4e1e3f5af41f68c48e589649ed4d
