### ISSUE TITLE
parsing params from URL like in RESTful

### ISSUE THREAD

**Issue by donmikel** [tarantool/nginx_upstream_module#45]
we have URL like this:
`http://www.example.com/users/323/orders?param1=10` 
or 
`http://www.example.com/users/323/messages?param1=10`

in nginx config we should write something like this:
```
server {
      # HTTP [GET | POST | PUT | DELETE] 
      location /users/:id/orders {
        # REST mode on
        tnt_http_rest_methods get
        tnt_method userOrders
        # Pass http headers and uri
        tnt_pass_http_request on;
        # Module on
        tnt_pass backend;
      }
```
Params from URL and QueryString will be merged into req.query lua table.
```
t['id'] = 323
t['param1'] = 10
```

**Comment by dedok** [comment]
tnt_pass_http_request on parse_args;

function call()
t['args'] = 323
t['args'] = 10

Is this what you want?
If yes then i close this one )

**Comment by dedok** [comment]
@donmikel

**Comment by dedok** [comment]
done see tnt_pass_http_request on parse_args;
