### ISSUE TITLE
REST Methods need

### ISSUE THREAD

**Issue by dsimonov** [tarantool/nginx_upstream_module#47]
Post, Get, Put, Patch, Delete

**Comment by aensidhe** [comment]
HTTP supports any method, so it is better not to limit to those strings, imho.

**Comment by dsimonov** [comment]
Its about REST methods

$ curl -s 'http://tarabaas.com:8080/tnt_rest?arg1=1&argN=N' -X DELETE --data '{"params": []}' | json_pp
{
   "id" : 0,
   "result" : [
      [
         {
            "headers" : {
               "Content-Type" : "application/x-www-form-urlencoded",
               "Content-Length" : "14",
               "Host" : "tarabaas.com:8080",
               "Accept" : "*/*",
               "User-Agent" : "curl/7.43.0"
            },
            "uri" : "/tnt_rest?arg1=1&argN=N"
         }
      ]
   ]
}

**Comment by dsimonov** [comment]
Речь о возможности узнавать метод запроса в объекте, передаваемом функции lux (в примерах именуемом req)

**Comment by dsimonov** [comment]
* функции lua

**Comment by dedok** [comment]
See #38
