### ISSUE TITLE
Add Docker images

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/nginx_upstream_module#49]
Add a Docker image with preconfigured nginx + nginx_upstream_module.

**Comment by racktear** [comment]
I've recently made a Dockerfile for nginx-based load balancer. It builds nginx from source:

https://gist.github.com/racktear/11c991cac133416aafa72491e4dedc37

**Comment by racktear** [comment]
Docker image created: https://hub.docker.com/r/tarantool/tarantool-nginx/

But we still need to document it, so I'm leaving this ticket open.

**Comment by dedok** [comment]
@racktear can I close the ticker?

**Comment by racktear** [comment]
yes

**Comment by dedok** [comment]
thx!
