### ISSUE TITLE
Feature request: Command for adding arbitrary headers

### ISSUE THREAD

**Issue by irqed** [tarantool/nginx_upstream_module#51]
Hello,

It would be nice to have a possibility to add a header before passing request to tnt.
I don't think it should work any different from `proxy_set_header` or `fastcgi_param`.

For example:

```
tnt_pass_http_request on;
tnt_set_header X-GEO-COUNTRY $geoip_country_code;
```

This should add X-GEO-COUNTRY value to req.headers table.

**Comment by dedok** [comment]
@irqed Hi. Do you need this feature ASAP? Or I can schedule to the next release

**Comment by Totktonada** [comment]
I would use `proxy_set_headers` to pass client IP to a tarantool instance, like so:

```
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by dedok** [comment]
in 1f057360b6a2425e31bd15fe890397e49687d748
