### ISSUE TITLE
Support new CALL command with EVAL-style marshalling (1.7.1+)

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/nginx_upstream_module#56]
Tarantool 1.7.1 adds a new implementation of CALL command which supports EVAL-style marshalling, i.e. returned data is not converted to tuples anymore. Old CALL command (code = 6) is deprecated.
Please detect Tarantool version on connect and use code=10 for CALL if remote version >= 1.7.1.

https://github.com/tarantool/tarantool/issues/1296

**Comment by mejedi** [comment]
After internal discussions we decided that selecting old or new `CALL` automatically based on the server version is a bad idea after all. Client code will notice the difference in semantics.

Instead we suggest the following: make call behave in `1.7` semantics by default. Add connection option to configure calls semantics. If user wants `1.6` `CALL`-s, she should say so explicitly.

**Comment by dedok** [comment]
Nginx module supports any type of result.
