### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by monopollly** [tarantool/nginx_upstream_module#60]
Please add this modules in Docker image:

```
- ngx_http_auth_jwt_module
- ngx_http_map_module
- https://github.com/openresty all;)
```

**Comment by dedok** [comment]
@racktear If you have chance, it would be great to see this feature, the feature is adding some modules at the build; or is it impossible?

**Comment by kamilion** [comment]
where do I get the source to ngx_http_auth_jwt_module? I can't find it anywhere, and this issue report is one of the only google results when I search for it.

**Comment by dedok** [comment]
Hi @kamilion, ngx_http_auth_jwt_module - this module is available as part of our commercial subscription. Here is details: https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html

**Comment by dedok** [comment]
@monopollly can I close this, or is this still actual?

**Comment by dedok** [comment]
Closed.
@monopollly just open the issue if you still have this issue.
