### ISSUE TITLE
tnt_auth

### ISSUE THREAD

**Issue by monopollly** [tarantool/nginx_upstream_module#61]
maybe a one more directive for security reason?
it will help to make a fast authorisation with nginx

```
tnt_auth = "somekey1"
tnt_auth = "somekey2"
tnt_auth = "somekey3"
```

and requests like this
{ "auth":"somekey1", "method": "echo", "params": [42, 23] }

**Comment by dedok** [comment]
Can you explain in details? What should tnt_auth do?

**Comment by dedok** [comment]
@monopollly ?

**Comment by dedok** [comment]
Closed till @monopollly will give me more details about this feature :)
