### ISSUE TITLE
Can't build module with readme script

### ISSUE THREAD

**Issue by jonywtf** [tarantool/nginx_upstream_module#62]
Hi! I have problems with building nginx_upstream_module on Ubuntu 16.04
```bash
sudo apt-get install libpcre-dev zlib1-dev
```
```
E: Unable to locate package libpcre-dev
E: Package 'zlib1-dev' has no installation candidate
```
i have used this command:
```bash
sudo apt install libpcre3-dev zlib1g-dev build-essential cmake
```
but after ```make build-all``` i can't find ngx_http_tnt_module.so

**Comment by dedok** [comment]
The fix can be found in latest version or master
