### ISSUE TITLE
Can't post data from echo.lua example

### ISSUE THREAD

**Issue by wprayudo** [tarantool/nginx_upstream_module#64]
2016/09/27 06:45:21 [crit] 31283#0: *5 [BUG] failed to complete output transcoding. UNKNOWN ERROR while reading response header from upstream, client: 127.0.0.1, server: tnt_test, request: "POST /echo HTTP/1.1", upstream: "tnt://127.0.0.1:10001", host: "127.0.0.1:8081"

I did make build-all-debug

**Comment by dedok** [comment]
@wprayudo Hi, which version of Tarantool do you use? I'll check this issue ASAP

**Comment by wprayudo** [comment]
it just worked once, and then appeared that error. I also tried all build options, and got the same error. I use the latest tarantool (1.7.1 ?)

**Comment by dedok** [comment]
I see, It could be problem like that https://github.com/tarantool/nginx_upstream_module/issues/56
Also, which version of nginx upstream do you use? (master or tag)

**Comment by wprayudo** [comment]
master

**Comment by dedok** [comment]
it was a problem with example, I removed location out of nginx conf (i.e. test/ngx_confs/tnt_server_test.conf) also tarantool does listened wrong port and host (i.e. example/echo.lua).

I fixed this. So let me know if you have a problem.

So if you using GUI(example/echo.html) you may post a echo ["1", "2"] and you will see a result Ok [4]{"id":4,"result":[["1"]]}

**Comment by dedok** [comment]
Also, I suggest to you use docker image for installing tarantool & nginx.
Nginx: https://hub.docker.com/r/tarantool/tarantool-nginx
Tarantool: https://hub.docker.com/r/tarantool/tarantool

**Comment by wprayudo** [comment]
ahaa, it works well now. thank you for help .

**Comment by dedok** [comment]
@wprayudo Thank you for bug report! :)
