### ISSUE TITLE
Possible memory corrupt if nginx has parallel too large requests (client_body_buffer_size)

### ISSUE THREAD

**Issue by dedok** [tarantool/nginx_upstream_module#69]
This issue It needs to be investigated. (each request has size around 52kb)

**Comment by dedok** [comment]
Not a bug, it was a error message: { 'error': { 'message':
                        "Request too large, consider increasing your server's setting 'client_body_buffer_size'",
                        'code': -32001 } }

**Comment by explosivebit** [comment]
Ok, thank you!
