### ISSUE TITLE
Handling pure POST request

### ISSUE THREAD

**Issue by fsitedev** [tarantool/nginx_upstream_module#76]
Currently if we need to send POST request there is only JSON-RPC technique available. It 's not convenient in some cases, for example simple html form submission.
"multipart/form-data" variant seems to be the most interesting, giving an ability to send binary data without encoding/escaping

**Comment by dedok** [comment]
I guess that I will handle content-type header to detect input type, for instance if content-type equals 'application/json' then I will use json transcoding and if content-type equals 'multipart/form-data' I will use  multipart transcoding.

But I still don't know how exactly does It work.

Let says we have follow POST
POST /
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Type: text/plain
Content-Disposition: form-data; name="title"

Missionary Portrait
--boundary
Content-Type: image/jpeg
Content-Disposition: form-data; filename="some.jpg"; name="some_name"

...(binary bytes of the image)...
--boundary--

Should I send everything as is, or should I parse body somehow?

For example 'as is':

``` lua
function tnt(req, ...)
  req.body - content of POST /
end
```

**Comment by fsitedev** [comment]
I think it must depend on "tnt_pass_http_request" option. You can provide value similar to "parse_args" but with more precise meaning, ex: "parse_body", "parse_post_body"

**Comment by dedok** [comment]
I see your point and I guess that makes sense :)

**Comment by dedok** [comment]
Hi!
The feature added (including auto tests).
For details see https://github.com/tarantool/nginx_upstream_module#tnt_pass_http_request (pass_body)
 Also you can get some examples here https://github.com/tarantool/nginx_upstream_module/blob/master/test/v24_features.py#L52

**Comment by dedok** [comment]
PS
Here is a configuration example - https://github.com/tarantool/nginx_upstream_module/blob/master/test/ngx_confs/tnt_server_test.conf#L230

**Comment by dedok** [comment]
@fsitedev is it work for you? Or maybe have you more cool ideas? :)

**Comment by fsitedev** [comment]
Yes, it's definitely great job 👍 
And of course I have ideas how to make it even more usefull: https://github.com/tarantool/nginx_upstream_module/issues/77
