### ISSUE TITLE
Parsing POST request

### ISSUE THREAD

**Issue by fsitedev** [tarantool/nginx_upstream_module#77]
As a continuation of the issue
https://github.com/tarantool/nginx_upstream_module/issues/76 I can suggest to parse the POST body and transfer resulting arguments into lua procedure.
It seems quite logical for modern web application to have such common things like request headers, GET-POST params and etc. not only in raw form but in commonly-used parsed variant.
As an Idea I can suggest to alter some options of "tnt_pass_http_request" directive:
- Rename "pass_body" to "pass_raw_body" only to show an explicit behaviour when no parsing applied in this case.
- Make "parse_body" (as analogue of parse_args). This option could enable automatic encoding resolvation. There are 3 common html-form encodings for now:
	- x-www-urlencoded (default if skipped)
	- multipart/form-data  (no encoding, split by boundaries)
	- text-plain (spaces replaced with "+")

So as not to die from so much work, we can start from only one encoding and add others one by one.
I'm sure this feature will make "tnt/nginx_upstream" much more convinient for end-level lua applications, which still suffer from heavy text-parsing tasks and will let them focus on it's logic only

**Comment by dedok** [comment]
x-www-urlencoded (default if skipped) in 1f057360b6a2425e31bd15fe890397e49687d748

**Comment by dedok** [comment]
You can found details in readme, here is a link https://github.com/tarantool/nginx_upstream_module#tnt_pass_http_request, check the urlencoded

**Comment by snoopcatt** [comment]
Added pull request that allow access to raw POST body even with `parse_urlencoded` enabled.
In my branch with `parse_urlencoded` there are new request variable — `args_urlencoded`, and you still have access to raw `body` value.

**Comment by dedok** [comment]
Yeah, I guess we can close this one. Thank you so much!
