### ISSUE TITLE
Return HTTP code 500 on Tarantool exceptions

### ISSUE THREAD

**Issue by racktear** [tarantool/nginx_upstream_module#82]
If Tarantool throws an exception from the function, this module should return HTTP 500 (Internal Server Error), and return exception text.

**Comment by racktear** [comment]
Also return HTTP 502 in case when the stored procedure doesn't return a header nginx expects when using `tnt_eval`.

**Comment by dedok** [comment]
Check 2.4.6. (https://github.com/tarantool/nginx_upstream_module#http-headers-and-status)
