### ISSUE TITLE
stack has overflowed if number of items more than uint16_t

### ISSUE THREAD

**Issue by dedok** [tarantool/nginx_upstream_module#84]
If client sends more than uint16_t elements in array or map, then nginx sends overflowed msgpack count of elements.

**Comment by dedok** [comment]
Referred to https://github.com/tarantool/tarantool/issues/2540

**Comment by elmirk** [comment]
we use nginx upstream module v2.6rc3 and nginx 1.13.6
we have tarantool crashed when test POST response with some kind of
wget 10.10.10.89:8081/pgw/v1 --header="Content-Type: application/json; charset=utf-8;" --post-data '{"myData":{"method":"testInfo","params":[{"msisdn":"92727111287" , "service":"service0"}],"id":1}}'

in tarantool logs then 
src/box/iproto.cc:682: void iproto_decode_msg(iproto_msg*, const char**, const char*, bool*): Assertion `*pos == reqend' failed.
