### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by shkuropat** [tarantool/nginx_upstream_module#90]
Please, update

**Comment by racktear** [comment]
What do you mean by "outdated docker image"?

**Comment by dedok** [comment]
That means that is latest stable version with new features is 3af386f6865a58f147a4b12672d0f0a5c7c96a3d. Docker has this version: 8290d60

**Comment by dedok** [comment]
in 1f057360b6a2425e31bd15fe890397e49687d748
