### ISSUE TITLE
Allow nginx variables for tnt_method

### ISSUE THREAD

**Issue by shkuropat** [tarantool/nginx_upstream_module#91]
Hi.
At this moment for 10 tarantool procedures, I need 10 tnt_pass methods.
I think something like this, will be very useful.

```
location ~ /tnt_proxy/([-_a-zA-Z0-9/]+) {
    tnt_method $1;
   ...
}
```

**Comment by dedok** [comment]
in 1f057360b6a2425e31bd15fe890397e49687d748
