### ISSUE TITLE
Docker image. Nginx error: unknown directive

### ISSUE THREAD

**Issue by icamys** [tarantool/nginx_upstream_module#99]
After updating docker image up to tag `v2.3.7` I'm getting error:

```
2017/09/04 15:40:18 [notice] 1#1: Tarantool upstream module, version: 'v2.3.6' in /etc/nginx/nginx.conf:18
2017/09/04 15:40:18 [emerg] 1#1: unknown directive "lua_need_request_body" in /etc/nginx/nginx.conf:60
```

Also notice that in logs there is still mentioned version 2.3.6, however 2.3.7 was installed.

If using `latest` tag, there is no any kind of error.

In readme is written that version 2.3.7 is production-ready so I think it should be classified as error.

**Comment by dedok** [comment]
Hi! We add more tags, so I think this issue can be closed. @icamys what do you think?

**Comment by opomuc** [comment]
All new tags does not reproduce it. @icamys feel free to comment if you are concerned. I will close the issue for now.
